pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Additional repository for SDL2 packages if needed
        maven { url 'https://jcenter.bintray.com' }
        maven { url 'https://maven.pkg.github.com/libsdl-org/*' }
    }
}
rootProject.name = "CXXGameApp"
include ':app'
