plugins {
    id 'com.android.application'
}

def selectedAbi = project.findProperty("ABI") ?: "arm64-v8a"

android {
    namespace 'com.example.cxxgame'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.cxxgame"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags ""

                arguments "-DANDROID_STL=c++_shared",
                          "-DSDL2_INCLUDE_DIR=${project.buildDir}/includes/SDL2",
                          "-DSDL2_LIB_DIR=${project.buildDir}/libs/SDL2",
                          "-DANDROID_ABI=${selectedAbi}"
            }
        }

        ndk {
            abiFilters selectedAbi
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
            version "3.22.1"
        }
    }
}
